export default Object.seal({
  email: 'Email',
  password: 'Password',
  forgotPassword: 'Forgot password',
  loginTitle: 'Login',
  loginBtn: 'LOGIN',
  alreadyRegistered: "Don't you have an account",
  registerHere: 'Register here',
  user: 'user@endava.com',
  welcomeMessage: 'Welcome',
  passwordChangedSuccessfully: 'Password changed successfully',
  loginErrorMessage: 'The entered data does not match any user.',
  loginErrorUnexpected: 'Unexpected error during login',
  userRegistered: 'User has been registered',
});
