import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import '@styles/theme.scss';
import '../globals.css';
import { Providers } from '../providers';
import { locales } from '@localization/index';
import { notFound } from 'next/navigation';

const geistSans = Geist({ variable: '--font-geist-sans', subsets: ['latin'] });
const geistMono = Geist_Mono({ variable: '--font-geist-mono', subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function LangLayout({ children, params }: { children: React.ReactNode; params: { lang: string } }) {
  const lang = (await params).lang;

  const locale = locales.find(l => l.id.toLowerCase() === lang.toLowerCase());
  if (!locale) return notFound();

  return (
    <html lang={lang}>
      <head>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers lang={lang}>{children}</Providers>
      </body>
    </html>
  );
}
